### ISSUE TITLE
[feat] SearchStartView 3차 UI 변경 대응

### ISSUE THREAD

**Issue by Guryss** [DeveloperAcademy-POSTECH/2024-MacC-A16-AGAMI#87]
## 🍏 About
* `SearchStartView` 3차 UI 변경 대응을 진행합니다. 

## 🍀 Branch Name
feat/#87

## 🌱 To do
- [x] SearchStartView

**Comment by ye-gang-jjang** [comment]
3차 변경이라니,, 화이팅 구리스
